server:
  port: 8888
  servlet:
    context-path: /UNIME

spring:
  datasource:
    url: "jdbc:mysql://root:fnkCycRqiVdqYfdEtAggsOEDsOvDtcpY@autorack.proxy.rlwy.net:41772/UnimeHospital"
    #    url: "jdbc:mysql://localhost:3306/unimehospital"
    #    url: "jdbc:mysql://avnadmin:AVNS_KYYfpmSdGpsQyLgPpYI@unimehospital-mysql-nguyenbaonhat06-6933.h.aivencloud.com:14561/UnimeHospital"
    username: root
    password: fnkCycRqiVdqYfdEtAggsOEDsOvDtcpY
  #    password: 2706phuongnhung
  #    password: AVNS_KYYfpmSdGpsQyLgPpYI

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true



#    open-in-view: false
jwt:
  signerKey: "4UXF7e8ExKlokbDG0p+/6ICPRLVRVt/GTksOF/+8p5vD+BiPaoKAJJbwmoywIcbv"
  valid-duration: 5
  refreshable-duration: 120
