server:
  port: 8888
  address: 0.0.0.0
  servlet:
    context-path: /UNIME



  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#    open-in-view: false
jwt:
  signerKey: "4UXF7e8ExKlokbDG0p+/6ICPRLVRVt/GTksOF/+8p5vD+BiPaoKAJJbwmoywIcbv"
  valid-duration: 5
  refreshable-duration: 120
