server:
  port: 8888
  address: 0.0.0.0
  servlet:
    context-path: /UNIME

spring:
  datasource:
    #    url: "jdbc:mysql://root:fnkCycRqiVdqYfdEtAggsOEDsOvDtcpY@autorack.proxy.rlwy.net:41772/UnimeHospital"
    #    url: "jdbc:mysql://localhost:3306/unimehospital"
    url: "jdbc:mysql://avnadmin:AVNS_KYYfpmSdGpsQyLgPpYI@unimehospital-mysql-nguyenbaonhat06-6933.h.aivencloud.com:14561/UnimeHospital"
    username: root
    #    password: fnkCycRqiVdqYfdEtAggsOEDsOvDtcpY
    #    password: 2706phuongnhung
    password: AVNS_KYYfpmSdGpsQyLgPpYI

  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#    open-in-view: false
jwt:
  signerKey: "4UXF7e8ExKlokbDG0p+/6ICPRLVRVt/GTksOF/+8p5vD+BiPaoKAJJbwmoywIcbv"
  valid-duration: 60 # in second
  refreshable-duration: 120 # in seconds
