name: CI/CD

on:
  push:
    branches:
      - main  # Triển khai khi có thay đổi trên nhánh main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to VPS
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USER: ${{ secrets.VPS_USER }}
          SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          # Lưu khóa SSH vào file key.pem
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem

          # Kiểm tra kết nối SSH
          echo "Testing SSH connection..."
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST "echo 'SSH connection successful!'"

          # Chạy deploy.sh trên VPS
          echo "Running deploy script..."
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST 'cd ~/springboot-app && bash deploy.sh'
          
          # Xóa khóa SSH sau khi sử dụng
          rm -f key.pem